/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PoolGame;

import java.io.IOException;
import java.util.List;

import PoolGame.Command.*;
import org.json.simple.parser.ParseException;

import PoolGame.ConfigReader.ConfigKeyMissingException;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.stage.Stage;

/** The JavaFX application */
public class App extends Application {

    public static final double FRAMETIME = 1.0 / 60.0;

    private LevelCommand[] levelCommands;

    private ConfigReader loadConfig(List<String> args) {
        String configPath;
        boolean isResourcesDir = false;
		if (args.size() > 0) {
			configPath = args.get(0);
		} else {
			// configPath = "src/main/resources/config.json";
			configPath = "/config.json";
            isResourcesDir = true;
		}
		// parse the file:
        ConfigReader config = null;
        try {
            config = new ConfigReader(configPath, isResourcesDir);
        } catch (IOException | ParseException | ConfigKeyMissingException | IllegalArgumentException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        }
        return config;
    }

    @Override
    public void start(Stage stage) {
        ConfigReader defaultConfig = loadConfig(getParameters().getRaw());

        stage.setTitle("PoolGame");
        stage.setResizable(false);

        Timeline timeline = new Timeline();
        timeline.setCycleCount(Timeline.INDEFINITE);

        this.levelCommands = new LevelCommand[4];
        this.levelCommands[0] = new DefaultLevelCommand(this.levelCommands,stage,timeline,defaultConfig);
        this.levelCommands[1] = new EasyLevelCommand(this.levelCommands,stage, timeline);
        this.levelCommands[2] = new NormalLevelCommand(this.levelCommands,stage, timeline);
        this.levelCommands[3] = new HardLevelCommand(this.levelCommands,stage, timeline);

        this.levelCommands[0].execute();

        stage.show();

    }

    /**
     * The entry point of the program
     * @param args CLI arguments
     */
    public static void main(String[] args) {
        launch(args);
    }
}
